query ($query: String!, $next_value: String) {
  #  rateLimit {
  #    cost
  #    remaining
  #    resetAt
  #  }
  search(query: $query, type: REPOSITORY, first: 100, after: $next_value) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ... on Repository {
        ...RepoFields
      }
    }
  }
}

fragment RepoFields on Repository {
  nameWithOwner
  pushedAt
  isArchived
  isDisabled
  defaultBranchRef {
    target {
      ... on Commit {
        oid
      }
    }
  }
  languages(first: 10, orderBy: { field: SIZE, direction: DESC }) {
    nodes {
      name
    }
  }
}
