name: GitHub Automatic Update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

permissions:
  contents: write

jobs:
  run_cron_github:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      GH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: repo
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: uv sync and install important things
        run: |
          cd ./src/readme_keyword_extraction

          uv sync

          uv run uvicorn main:app --host 0.0.0.0 --port 8000 &

      - name: wait for 20 seconds before starting, for server to start
        run: |
          sleep 20
          curl http://127.0.0.1:8000/extract_keywords

      - name: Download cron-github binary
        run: wget -O cron-github https://github.com/Zigistry/database/releases/download/executables/cron-github

      - name: Download database
        run: wget -O ./zigistry.db https://github.com/Zigistry/database/releases/download/database/zigistry.db

      - name: Make binary executable
        run: chmod +x ./cron-github

      - name: Run cron-github
        run: ./cron-github

      - name: push updated database
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload database ./zigistry.db --clobber
